services:
  api:
    image: golang:1.20-alpine
    container_name: go_api
    build:
      context: ./api
    working_dir: /app
    volumes:
      - ./api:/app
    expose:
      - "8080"  # Expose le port interne de l'API pour que Nginx puisse y accéder
    depends_on:
      - db
    networks:
      - app_network


  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin
      MYSQL_USER: lukyss
      MYSQL_PASSWORD: lukyss
    ports:
      - "3306:33060"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8085:80"
    depends_on:
      - api
    networks:
      - app_network

  # jenkins:
  #   container_name: jenkins
  #   build:
  #     context: ./jenkins
  #   ports:
  #     - "8081:8080"
  #     - "50000:50000"
  #   volumes:
  #     - jenkins_data:/var/jenkins_home
  #   networks:
  #     - app_network

volumes:
  db_data:
  # jenkins_data:

networks:
  app_network:
    driver: bridge
